name: Context Examples

on: [push]

jobs: 
 my-context: 
   runs-on: ubuntu-latest
   steps: 
     - name: step1
       run: echo "The action is $my_action" 
       env: 
         my_action: ${{ github.action }}